package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
)

func TestFunctionsMDStaleness(t *testing.T) {
	// Generate expected markdown in memory using shared logic
	expected := generateMarkdown()

	// Read existing functions.md
	existingPath := "../../../functions.md"
	existingBytes, err := os.ReadFile(existingPath)
	if err != nil {
		t.Fatalf("Failed to read existing %s: %v", existingPath, err)
	}

	existing := string(existingBytes)

	if expected != existing {
		t.Errorf("functions.md is stale. Please run 'go run ./cmd/docs/genfunctionmd' to regenerate it.\n\nDiff check failed.")
	}
}

func TestExecuteGenerator(t *testing.T) {
	tempDir := t.TempDir()

	ext := ""
	if runtime.GOOS == "windows" {
		ext = ".exe"
	}
	binPath := filepath.Join(tempDir, "genfunctionmd"+ext)

	// Build the generator
	buildCmd := exec.Command("go", "build", "-o", binPath, "./cmd/docs/genfunctionmd")
	buildCmd.Dir = "../../.." // Run from repo root
	if out, err := buildCmd.CombinedOutput(); err != nil {
		t.Fatalf("Failed to build generator: %v\nOutput: %s", err, out)
	}

	// Create a safe execution directory
	runDir := t.TempDir()

	// Execute the built generator
	runCmd := exec.Command(binPath)
	runCmd.Dir = runDir
	if out, err := runCmd.CombinedOutput(); err != nil {
		t.Fatalf("Failed to execute generator: %v\nOutput: %s", err, out)
	}

	// Read the generated file from the temp run directory
	genPath := filepath.Join(runDir, "functions.md")
	genBytes, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("Failed to read generated functions.md: %v", err)
	}

	// Read existing tracked functions.md
	existingPath := "../../../functions.md"
	existingBytes, err := os.ReadFile(existingPath)
	if err != nil {
		t.Fatalf("Failed to read existing %s: %v", existingPath, err)
	}

	if string(genBytes) != string(existingBytes) {
		t.Errorf("functions.md generated by executable differs from checked-in functions.md")
	}
}
